import '../models/medical_field_model.dart';
import '../models/doctor_model.dart';
import '../models/medicine.dart';
import '../models/content_model.dart';
import '../models/app_user.dart';
import '../models/appointment_model.dart';
import '../models/reminder_model.dart';

class MockData {
  static final AppUser sampleUser = AppUser(
    id: 'usr_demo_101',
    name: 'Sarah Connor',
    age: 34,
    language: 'English',
    allergies: ['Penicillin', 'Sulfa drugs'],
    currentMedicines: ['Metformin 850mg', 'Lisinopril 10mg'],
  );

  static final List<MedicalField> medicalFields = [
    MedicalField(
      id: 'mf_01',
      fieldName: 'General Medicine',
      description: 'Primary healthcare Q&A, comprehensive consultations, wellness screenings, and medication management.',
      conditions: ['Common Cold & Flu', 'Hypertension', 'Type 2 Diabetes', 'Fever & Infections', 'Fatigue'],
      safetyTips: ['Get annual health checkups.', 'Stay hydrated and eat balanced meals.', 'Do not self-prescribe antibiotics.'],
      doctorIds: ['doc_gen_1', 'doc_gen_2'],
      symptomsAndWarnings: ['High fever lasting > 3 days', 'Unexplained severe fatigue', 'Sudden rapid weight loss'],
      emergencyGuidance: 'If experiencing severe confusion, high fever with stiff neck, or extreme lethargy, call emergency response.',
      iconName: 'health_and_safety',
    ),
    MedicalField(
      id: 'mf_02',
      fieldName: 'Cardiology',
      description: 'Heart and cardiovascular system care, blood pressure monitoring, and cardiac risk assessment.',
      conditions: ['Coronary Artery Disease', 'High Blood Pressure', 'Arrhythmia', 'Heart Failure', 'Hyperlipidemia'],
      safetyTips: ['Monitor BP daily if diagnosed.', 'Limit sodium intake to under 2,000mg/day.', 'Engage in 30 mins moderate daily cardio.'],
      doctorIds: ['doc_card_1', 'doc_card_2'],
      symptomsAndWarnings: ['Chest tightness or pressure', 'Pain radiating to jaw or left arm', 'Shortness of breath on exertion'],
      emergencyGuidance: 'CHEST PAIN EMERGENCY: Crushing chest pain or pressure requires IMMEDIATE emergency assistance (Dial 911 / 112).',
      iconName: 'favorite',
    ),
    MedicalField(
      id: 'mf_03',
      fieldName: 'Dermatology',
      description: 'Skin, hair, and nail health, rash evaluation, acne treatment, and lesion monitoring.',
      conditions: ['Eczema & Dermatitis', 'Psoriasis', 'Acne Vulgaris', 'Fungal Skin Infections', 'Skin Lesions & Moles'],
      safetyTips: ['Apply SPF 30+ sunscreen daily.', 'Avoid picking or popping inflammatory acne.', 'Monitor changes in mole size and shape (ABCDE rule).'],
      doctorIds: ['doc_derm_1'],
      symptomsAndWarnings: ['Rapidly spreading red rash', 'Skin lesions that bleed or change color', 'Blistering with fever'],
      emergencyGuidance: 'Sudden widespread skin blistering or facial swelling with difficulty breathing requires immediate emergency care.',
      iconName: 'face',
    ),
    MedicalField(
      id: 'mf_04',
      fieldName: 'Dentistry',
      description: 'Oral hygiene, tooth pain evaluation, gum disease treatment, and dental preventive procedures.',
      conditions: ['Tooth Decay (Caries)', 'Gingivitis & Periodontitis', 'Tooth Abscess', 'Bruxism (Teeth Grinding)', 'Sensitivity'],
      safetyTips: ['Brush twice daily with fluoride toothpaste.', 'Floss daily between teeth.', 'Visit a dentist every 6 months.'],
      doctorIds: ['doc_dent_1'],
      symptomsAndWarnings: ['Severe throbbing tooth pain', 'Facial swelling around jaw', 'Pus discharge from gums'],
      emergencyGuidance: 'Facial swelling spreading to eye or neck from tooth infection is an emergency; seek immediate hospital or dental triage.',
      iconName: 'clean_hands',
    ),
    MedicalField(
      id: 'mf_05',
      fieldName: 'Pediatrics',
      description: 'Comprehensive health, growth tracking, and vaccination management for infants, children, and adolescents.',
      conditions: ['Childhood Asthma', 'Otitis Media (Ear Infection)', 'Chickenpox / Measles', 'Growth Delay', 'Infant Colic'],
      safetyTips: ['Keep childhood vaccination schedules up to date.', 'Store all medicines in childproof locked cabinets.', 'Ensure adequate hydration during fever.'],
      doctorIds: ['doc_ped_1'],
      symptomsAndWarnings: ['High fever in infants under 3 months', 'Lethargy or unresponsiveness', 'Stridor / difficulty breathing'],
      emergencyGuidance: 'High fever in newborns (< 90 days) or severe respiratory distress in infants requires urgent ER evaluation.',
      iconName: 'child_care',
    ),
    MedicalField(
      id: 'mf_06',
      fieldName: 'Gynecology',
      description: 'Women’s reproductive health, menstrual disorders, prenatal guidance, and hormonal wellness.',
      conditions: ['PCOS & Endometriosis', 'Menstrual Irregularities', 'Pregnancy Care', 'UTI & Vaginitis', 'Menopause Management'],
      safetyTips: ['Schedule annual Pap smear screenings as recommended.', 'Track menstrual cycles routinely.', 'Maintain pelvic floor exercises.'],
      doctorIds: ['doc_gyn_1'],
      symptomsAndWarnings: ['Heavy bleeding soaking > 2 pads/hour', 'Severe acute lower abdominal pain', 'High fever during pregnancy'],
      emergencyGuidance: 'Severe lower abdominal pain with fainting or heavy pregnancy bleeding requires immediate emergency transport.',
      iconName: 'pregnant_woman',
    ),
    MedicalField(
      id: 'mf_07',
      fieldName: 'Orthopedics',
      description: 'Bone, joint, ligament, and skeletal system diagnosis, fracture care, and arthritis management.',
      conditions: ['Osteoarthritis', 'Bone Fractures', 'ACL & Ligament Tears', 'Carpal Tunnel Syndrome', 'Scoliosis'],
      safetyTips: ['Maintain calcium and Vitamin D intake.', 'Practice proper lifting techniques.', 'Wear protective gear during sports.'],
      doctorIds: ['doc_ortho_1'],
      symptomsAndWarnings: ['Inability to bear weight on limb', 'Visible bone deformity', 'Sudden severe joint swelling'],
      emergencyGuidance: 'Open fractures or limb numbness after trauma are medical emergencies; immobilize limb and call emergency response.',
      iconName: 'accessibility_new',
    ),
    MedicalField(
      id: 'mf_08',
      fieldName: 'Physiotherapy',
      description: 'Rehabilitation therapy, post-surgical recovery, spinal mobility, and ergonomic alignment.',
      conditions: ['Post-Op Joint Recovery', 'Chronic Back & Neck Pain', 'Frozen Shoulder', 'Sciatica', 'Stroke Rehab'],
      safetyTips: ['Perform prescribed exercises daily.', 'Take regular movement breaks during desk work.', 'Maintain posture alignment.'],
      doctorIds: ['doc_physio_1'],
      symptomsAndWarnings: ['Loss of bowel/bladder control with back pain', 'Sudden leg weakness', 'Severe shooting numbness'],
      emergencyGuidance: 'Sudden loss of bowel or bladder control with back pain may indicate Cauda Equina Syndrome; seek emergency ER care immediately.',
      iconName: 'fitness_center',
    ),
    MedicalField(
      id: 'mf_09',
      fieldName: 'Psychiatry/Psychology',
      description: 'Mental health assessment, mood regulation, anxiety treatment, and psychological support.',
      conditions: ['Major Depressive Disorder', 'Generalized Anxiety', 'Bipolar Disorder', 'PTSD', 'Insomnia'],
      safetyTips: ['Maintain consistent sleep hygiene.', 'Practice mindfulness and deep breathing.', 'Reach out for professional support early.'],
      doctorIds: ['doc_psych_1'],
      symptomsAndWarnings: ['Thoughts of self-harm or suicide', 'Severe prolonged insomnia', 'Panic attacks with hyperventilation'],
      emergencyGuidance: 'If experiencing suicidal crisis or acute panic breakdown, immediately contact the Suicide & Crisis Lifeline (988) or emergency services.',
      iconName: 'psychology',
    ),
    MedicalField(
      id: 'mf_10',
      fieldName: 'Neurology',
      description: 'Brain, spinal cord, and nerve disorder evaluation, migraine care, and seizure management.',
      conditions: ['Migraine & Tension Headaches', 'Epilepsy & Seizures', 'Parkinson’s Disease', 'Multiple Sclerosis', 'Peripheral Neuropathy'],
      safetyTips: ['Maintain a headache/trigger diary.', 'Never skip anti-epileptic medications.', 'Protect head with helmets during biking.'],
      doctorIds: ['doc_neuro_1'],
      symptomsAndWarnings: ['Sudden "thunderclap" headache', 'Facial drooping or slurred speech (FAST)', 'Loss of vision in one eye'],
      emergencyGuidance: 'STROKE ALERT: Sudden facial drooping, arm weakness, or slurred speech requires IMMEDIATE stroke center emergency care.',
      iconName: 'biotech',
    ),
    MedicalField(
      id: 'mf_11',
      fieldName: 'Pulmonology',
      description: 'Respiratory system health, lung function testing, asthma guidance, and COPD therapy.',
      conditions: ['Asthma', 'COPD & Emphysema', 'Pneumonia', 'Bronchitis', 'Sleep Apnea'],
      safetyTips: ['Avoid smoking and secondhand smoke.', 'Use rescue inhalers exactly as prescribed.', 'Get annual flu and pneumococcal vaccines.'],
      doctorIds: ['doc_pulm_1'],
      symptomsAndWarnings: ['Cyanosis (blue lips or nails)', 'Inability to speak in full sentences due to breathlessness', 'Chest wall indrawing'],
      emergencyGuidance: 'Severe asthma attack with blue lips or gasping for air is a lifethreatening emergency. Call 911 immediately.',
      iconName: 'air',
    ),
    MedicalField(
      id: 'mf_12',
      fieldName: 'Gastroenterology',
      description: 'Digestive system, liver, stomach, and bowel disease diagnosis and nutritional absorption care.',
      conditions: ['GERD / Acid Reflux', 'Irritable Bowel Syndrome (IBS)', 'Peptic Ulcer Disease', 'Fatty Liver Disease', 'Crohn’s & Colitis'],
      safetyTips: ['Eat small, frequent fiber-rich meals.', 'Limit excessive NSAID painkiller use.', 'Avoid lying down for 2 hours post-meal.'],
      doctorIds: ['doc_gastro_1'],
      symptomsAndWarnings: ['Vomiting blood or coffee-ground material', 'Black tarry stools', 'Severe acute right-lower abdominal pain'],
      emergencyGuidance: 'Vomiting blood or severe right-lower quadrant stomach pain (possible appendicitis) requires emergency room triage.',
      iconName: 'restaurant',
    ),
    MedicalField(
      id: 'mf_13',
      fieldName: 'Nephrology',
      description: 'Kidney health, filtration monitoring, electrolyte balance, and chronic kidney disease management.',
      conditions: ['Chronic Kidney Disease (CKD)', 'Kidney Stones', 'Glomerulonephritis', 'Diabetic Nephropathy', 'Electrolyte Imbalance'],
      safetyTips: ['Drink 2 to 2.5 liters of water daily.', 'Control blood sugar and blood pressure.', 'Avoid unnecessary over-the-counter NSAIDs.'],
      doctorIds: ['doc_neph_1'],
      symptomsAndWarnings: ['Sudden decrease in urination', 'Severe flank pain radiating to groin', 'Swelling in feet and face (edema)'],
      emergencyGuidance: 'Sudden complete absence of urine output or severe excruciating flank pain needs immediate emergency evaluation.',
      iconName: 'water_drop',
    ),
    MedicalField(
      id: 'mf_14',
      fieldName: 'Urology',
      description: 'Urinary tract, bladder, and male reproductive health evaluation and minimally invasive procedures.',
      conditions: ['Urinary Tract Infections (UTI)', 'Benign Prostatic Hyperplasia (BPH)', 'Bladder Incontinence', 'Prostatitis', 'Hydrocele'],
      safetyTips: ['Complete the full course of prescribed antibiotics.', 'Do not hold urine for extended periods.', 'Maintain prostate health checks after age 50.'],
      doctorIds: ['doc_uro_1'],
      symptomsAndWarnings: ['Gross hematuria (blood in urine)', 'Inability to pass urine', 'High fever with severe chills and flank pain'],
      emergencyGuidance: 'Acute urinary retention (unable to urinate despite fullness) is an emergency requiring catheter relief.',
      iconName: 'medication',
    ),
    MedicalField(
      id: 'mf_15',
      fieldName: 'Oncology',
      description: 'Cancer screening, chemotherapy guidance, side-effect management, and supportive oncology care.',
      conditions: ['Breast Cancer Screening', 'Lung & Colorectal Cancer', 'Lymphoma & Leukemia', 'Chemotherapy Side Effects', 'Radiation Recovery'],
      safetyTips: ['Adhere strictly to oncologic appointment schedules.', 'Report post-chemo fever immediately.', 'Maintain high nutritional calorie support.'],
      doctorIds: ['doc_onco_1'],
      symptomsAndWarnings: ['Fever > 100.4°F (38°C) while on chemotherapy', 'Severe intractable nausea/vomiting', 'Unexplained lump'],
      emergencyGuidance: 'Neutropenic fever during chemotherapy is a medical emergency requiring urgent IV antibiotics at the hospital.',
      iconName: 'science',
    ),
    MedicalField(
      id: 'mf_16',
      fieldName: 'Ophthalmology',
      description: 'Eye care, vision testing, glaucoma screening, cataract evaluation, and retinal health.',
      conditions: ['Cataract', 'Glaucoma', 'Diabetic Retinopathy', 'Conjunctivitis (Pink Eye)', 'Dry Eye Syndrome'],
      safetyTips: ['Wear protective eyewear during hazardous activities.', 'Take 20-20-20 screen breaks.', 'Get annual dilated eye exams if diabetic.'],
      doctorIds: ['doc_ophthalm_1'],
      symptomsAndWarnings: ['Sudden painless vision loss', 'Flashes of light or shower of floaters', 'Severe eye pain with redness and halos'],
      emergencyGuidance: 'Sudden vision loss or flashes/curtain over vision (retinal detachment / acute glaucoma) requires emergency eye surgery triage.',
      iconName: 'visibility',
    ),
    MedicalField(
      id: 'mf_17',
      fieldName: 'ENT',
      description: 'Ear, Nose, and Throat diagnostics, sinus management, hearing evaluation, and voice care.',
      conditions: ['Sinusitis', 'Tonsillitis & Pharyngitis', 'Vertigo & Inner Ear Disorders', 'Tinnitus & Hearing Loss', 'Nasal Polyps'],
      safetyTips: ['Never insert cotton swabs deep into ear canals.', 'Humidify room air during sinus infections.', 'Protect ears from loud (>85dB) noise.'],
      doctorIds: ['doc_ent_1'],
      symptomsAndWarnings: ['Sudden unilateral hearing loss', 'Inability to swallow saliva due to throat swelling', 'Severe nosebleed > 20 mins'],
      emergencyGuidance: 'Throat swelling causing difficulty swallowing or breathing is an airway emergency. Call 911 immediately.',
      iconName: 'hearing',
    ),
    MedicalField(
      id: 'mf_18',
      fieldName: 'Endocrinology',
      description: 'Hormone balance, thyroid disorder management, blood sugar control, and metabolic health.',
      conditions: ['Type 1 & Type 2 Diabetes', 'Hypothyroidism / Hyperthyroidism', 'Osteoporosis', 'Adrenal Insufficiency', 'Pituitary Disorders'],
      safetyTips: ['Check blood glucose as advised.', 'Take thyroid medications on an empty stomach in the morning.', 'Carry fast-acting glucose for hypos.'],
      doctorIds: ['doc_endo_1'],
      symptomsAndWarnings: ['Severe hypoglycemia (sweating, confusion, shakiness)', 'Kussmaul breathing / fruity breath (DKA)', 'Extreme thirst and urination'],
      emergencyGuidance: 'Diabetic Ketoacidosis (DKA) or unresponsiveness from low blood sugar requires immediate emergency glucagon/ER care.',
      iconName: 'monitor_heart',
    ),
    MedicalField(
      id: 'mf_19',
      fieldName: 'Nutrition and Dietetics',
      description: 'Clinical nutrition counseling, meal planning for chronic diseases, weight management, and deficiency care.',
      conditions: ['Malnutrition / Vitamin Deficiencies', 'Obesity & Metabolic Syndrome', 'Renal / Diabetic Meal Planning', 'Celiac Disease', 'Food Intolerances'],
      safetyTips: ['Prioritize whole, unprocessed foods.', 'Ensure balanced macronutrients per meal.', 'Consult a dietitian for custom therapeutic diets.'],
      doctorIds: ['doc_nutri_1'],
      symptomsAndWarnings: ['Rapid involuntary weight loss > 10% in 1 month', 'Severe electrolyte imbalance from purging', 'Extreme weakness'],
      emergencyGuidance: 'Severe dehydration or electrolyte crash needs urgent IV rehydration.',
      iconName: 'set_meal',
    ),
    MedicalField(
      id: 'mf_20',
      fieldName: 'Emergency Medicine',
      description: 'First-aid protocols, trauma triage, acute resuscitation guidance, and emergency transport coordination.',
      conditions: ['Trauma & Fractures', 'Acute Anaphylaxis', 'Poisoning & Overdose', 'Severe Heat Stroke', 'Cardiac Arrest'],
      safetyTips: ['Keep emergency contact numbers saved.', 'Maintain a certified Home First-Aid Kit.', 'Learn CPR and AED operation.'],
      doctorIds: ['doc_em_1'],
      symptomsAndWarnings: ['Loss of consciousness', 'Uncontrollable bleeding', 'Severe chest pain or stroke signs'],
      emergencyGuidance: 'FOR ALL LIFE-THREATENING EMERGENCIES: IMMEDIATELY DIAL LOCAL EMERGENCY HOTLINE (911 / 112 / 102).',
      iconName: 'local_hospital',
    ),
  ];

  static final List<DoctorProfile> doctors = [
    DoctorProfile(
      id: 'doc_gen_1',
      name: 'Dr. Arthur Pendelton',
      specialty: 'General Medicine',
      qualification: 'MD, Internal Medicine (Johns Hopkins)',
      location: 'Downtown Health Plaza, Suite 402',
      availability: [TimeSlot(day: 'Mon, Wed, Fri', time: '09:00 AM - 02:00 PM')],
      consultationType: ConsultationType.both,
      rating: 4.9,
      experienceYears: 14,
      hospital: 'Metropolitan General Hospital',
    ),
    DoctorProfile(
      id: 'doc_card_1',
      name: 'Dr. Elena Rostova',
      specialty: 'Cardiology',
      qualification: 'MD, FACC, Interventional Cardiology',
      location: 'St. Jude Heart Center, Wing B',
      availability: [TimeSlot(day: 'Tue, Thu', time: '10:00 AM - 04:00 PM')],
      consultationType: ConsultationType.in_person,
      rating: 5.0,
      experienceYears: 18,
      hospital: 'St. Jude Heart Institute',
    ),
    DoctorProfile(
      id: 'doc_derm_1',
      name: 'Dr. Marcus Vance',
      specialty: 'Dermatology',
      qualification: 'MD, FAAD, Cosmetic & Medical Derm',
      location: 'ClearSkin Clinic, 7th Ave',
      availability: [TimeSlot(day: 'Mon, Tue, Fri', time: '11:00 AM - 05:00 PM')],
      consultationType: ConsultationType.both,
      rating: 4.8,
      experienceYears: 9,
      hospital: 'Apex Dermatology Center',
    ),
    DoctorProfile(
      id: 'doc_dent_1',
      name: 'Dr. Sophia Lin',
      specialty: 'Dentistry',
      qualification: 'DDS, Endodontics & Cosmetic Dentistry',
      location: 'Smile Studio, Oak Ridge',
      availability: [TimeSlot(day: 'Mon-Sat', time: '09:00 AM - 06:00 PM')],
      consultationType: ConsultationType.in_person,
      rating: 4.9,
      experienceYears: 11,
      hospital: 'HeartBeat Dental Facility',
    ),
    DoctorProfile(
      id: 'doc_ped_1',
      name: 'Dr. David Miller',
      specialty: 'Pediatrics',
      qualification: 'MD, FAAP, Child Healthcare',
      location: 'Sunshine Children\'s Clinic',
      availability: [TimeSlot(day: 'Mon-Fri', time: '08:30 AM - 03:30 PM')],
      consultationType: ConsultationType.both,
      rating: 4.9,
      experienceYears: 15,
      hospital: 'Children\'s Memorial Hospital',
    ),
    DoctorProfile(
      id: 'doc_neuro_1',
      name: 'Dr. Maya Patel',
      specialty: 'Neurology',
      qualification: 'MD, DM Neurology, Brain & Nerve Specialist',
      location: 'NeuroScience Institute, North Block',
      availability: [TimeSlot(day: 'Wed, Sat', time: '01:00 PM - 07:00 PM')],
      consultationType: ConsultationType.video,
      rating: 4.9,
      experienceYears: 16,
      hospital: 'NeuroScience Medical Center',
    ),
  ];

  static final List<Medicine> medicines = [
    Medicine(
      id: 'med_01',
      medicineName: 'Amoxicillin 500mg',
      genericName: 'Amoxicillin',
      uses: ['Bacterial Infections', 'Strep Throat', 'Otitis Media', 'Pneumonia'],
      precautions: ['Take with food if stomach upset occurs.', 'Complete full antibiotic course even if feeling better.'],
      sideEffects: ['Diarrhea', 'Nausea', 'Mild rash'],
      interactions: ['Penicillin', 'Allopurinol', 'Oral Contraceptives'],
      category: 'Antibiotic',
      dosageForm: 'Capsule',
      standardDosage: '500mg every 8 hours for 7-10 days',
    ),
    Medicine(
      id: 'med_02',
      medicineName: 'Ibuprofen 400mg',
      genericName: 'Ibuprofen',
      uses: ['Pain Relief', 'Fever Reduction', 'Anti-Inflammatory', 'Headache', 'Arthritis'],
      precautions: ['Always take after meals.', 'Avoid if history of stomach ulcers or severe kidney disease.'],
      sideEffects: ['Heartburn', 'Stomach ache', 'Dizziness'],
      interactions: ['Aspirin', 'Warfarin', 'Lisinopril', 'Methotrexate'],
      category: 'NSAID / Analgesic',
      dosageForm: 'Tablet',
      standardDosage: '400mg every 6-8 hours after meals',
    ),
    Medicine(
      id: 'med_03',
      medicineName: 'Metformin 850mg',
      genericName: 'Metformin',
      uses: ['Type 2 Diabetes Mellitus', 'Blood Glucose Control', 'PCOS Insulin Resistance'],
      precautions: ['Take with evening meal.', 'Monitor kidney function (eGFR) regularly.'],
      sideEffects: ['Metallic taste', 'Abdominal bloating', 'Mild diarrhea'],
      interactions: ['Contrast Dyes', 'Cimetidine', 'Alcohol'],
      category: 'Antidiabetic',
      dosageForm: 'Extended Release Tablet',
      standardDosage: '850mg once daily with dinner',
    ),
    Medicine(
      id: 'med_04',
      medicineName: 'Lisinopril 10mg',
      genericName: 'Lisinopril',
      uses: ['Hypertension', 'Heart Failure Management', 'Post-Myocardial Infarction'],
      precautions: ['Monitor blood pressure and serum potassium.', 'Avoid potassium supplements without doctor advice.'],
      sideEffects: ['Dry cough', 'Dizziness', 'Headache'],
      interactions: ['Ibuprofen', 'Spironolactone', 'Lithium'],
      category: 'ACE Inhibitor',
      dosageForm: 'Tablet',
      standardDosage: '10mg once daily in the morning',
    ),
    Medicine(
      id: 'med_05',
      medicineName: 'Aspirin 81mg',
      genericName: 'Aspirin',
      uses: ['Cardiovascular Risk Reduction', 'Blood Thinning', 'Pain Relief'],
      precautions: ['Do not give to children/teenagers due to Reye Syndrome risk.', 'Watch for bleeding signs.'],
      sideEffects: ['Stomach irritation', 'Easy bruising'],
      interactions: ['Ibuprofen', 'Warfarin', 'Clopidogrel'],
      category: 'Antiplatelet',
      dosageForm: 'Enteric Coated Tablet',
      standardDosage: '81mg once daily with water',
    ),
    Medicine(
      id: 'med_06',
      medicineName: 'Omeprazole 20mg',
      genericName: 'Omeprazole',
      uses: ['GERD Acid Reflux', 'Peptic Ulcers', 'Heartburn Relief'],
      precautions: ['Take 30 minutes before first meal of the day.', 'Do not crush capsule.'],
      sideEffects: ['Headache', 'Flatulence', 'Abdominal pain'],
      interactions: ['Clopidogrel', 'Ketoconazole', 'Methotrexate'],
      category: 'Proton Pump Inhibitor',
      dosageForm: 'Capsule',
      standardDosage: '20mg once daily 30 minutes before breakfast',
    ),
  ];

  static final List<EducationalContent> contentList = [
    EducationalContent(
      id: 'cnt_01',
      fieldName: 'Cardiology',
      title: 'Understanding Blood Pressure & Heart Health',
      description: 'An educational breakdown of systolic vs diastolic blood pressure, key risk factors, and heart-healthy habit guidelines.',
      imageUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=600&q=80',
      videoUrl: 'https://www.youtube.com/watch?v=sample_cardio',
      reviewDate: '2026-08-15',
      contentType: 'photo',
    ),
    EducationalContent(
      id: 'cnt_02',
      fieldName: 'Dermatology',
      title: 'Daily Skincare & Sun Protection Protocol',
      description: 'Learn how UVA/UVB rays impact skin tissue and how to correctly select broad-spectrum non-comedogenic sunscreen.',
      imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80',
      videoUrl: '',
      reviewDate: '2026-08-10',
      contentType: 'photo',
    ),
    EducationalContent(
      id: 'cnt_03',
      fieldName: 'Physiotherapy',
      title: 'Ergonomic Desk Stretching & Lumbar Relief',
      description: 'Guided physical therapy video demonstrating 5 core movement routines to relieve lower back tension.',
      imageUrl: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=600&q=80',
      videoUrl: 'https://www.youtube.com/watch?v=sample_physio',
      reviewDate: '2026-08-18',
      contentType: 'video',
    ),
  ];

  static final List<Appointment> appointments = [
    Appointment(
      id: 'apt_101',
      patientId: 'usr_demo_101',
      doctorId: 'doc_card_1',
      doctorName: 'Dr. Elena Rostova',
      specialty: 'Cardiology',
      date: '2026-09-02',
      time: '10:30 AM',
      status: AppointmentStatus.confirmed,
      notes: 'Routine BP evaluation & ECG review',
    ),
  ];

  static final List<HealthReminder> reminders = [
    HealthReminder(
      id: 'rem_201',
      userId: 'usr_demo_101',
      reminderType: 'medicine',
      title: 'Take Metformin 850mg (with Dinner)',
      date: 'Daily',
      time: '08:00 PM',
      isActive: true,
    ),
    HealthReminder(
      id: 'rem_202',
      userId: 'usr_demo_101',
      reminderType: 'medicine',
      title: 'Take Lisinopril 10mg',
      date: 'Daily',
      time: '08:00 AM',
      isActive: true,
    ),
  ];
}
